name: My First Workflows
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - name: Show Message
        run: echo "🤗 Hello World!"

      - name: List files in repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree

      - name: Checkout
        uses: actions/checkout@v4

      - name: List files in repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
